apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: web-app
    releaseName: daedalus
    repo: https://naturalselectionlabs.github.io/helm-charts
    valuesFile: values.yaml
    version: 0.x.x
