image:
  repository: rss3/daedalus

workload:
  name: daedalus

ingressRoute:
  enabled: true
  entryPoints: ["websecure"]
  routes:
    - Host(`daedalus.dev.nsl.xyz`)
  tls:
    secretName: daedalus-cert

org:
  team: devops
