name: "Daedalus"
description: "Build CI"
inputs:
  name:
    required: true
    description: application name
  namespace:
    required: true
    description: application namespace
  cluster:
    required: true
    description: application cluster

outputs:
  app: # id of output
    description: "Argo CD app yaml"
runs:
  using: node20
  main: dist/index.ts
