# deploy to kubernetes workflow
name: Deploy to Kubernetes
on:
  workflow_call:
    inputs:
      version:
        description: "Kubectl version"
        default: "latest"
        required: false
        type: string
      cluster:
        description: "Kubernetes cluster"
        required: true
        type: string
      namespace:
        description: "Kubernetes cluster namespace"
        required: true
        type: string
      images:
        description: "The image name"
        required: true
        type: string
      tag:
        description: "The image tag"
        required: true
        type: string
      releaseName:
        description: "The release name"
        required: true
        type: string
      chart:
        description: "Helm chart"
        required: false
        type: string
        default: web-app
      overrideFiles:
        description: "Override files"
        required: false
        type: string
        default: values.yaml
      overrides:
        description: "Override values"
        required: false
        type: string
      helm-chart-version:
        description: Helm Chart version
        required: false
        default: x.x.x
        type: string
      repoUrl:
        description: "Helm repo url"
        required: false
        type: string
        default: "https://naturalselectionlabs.github.io/helm-charts"
      kustomize-dir:
        required: false
        type: string
      manifests:
        description: "Manifests"
        required: false
        type: string
    secrets:
      ACCESS_KEY_ID:
        required: true
      ACCESS_KEY_SECRET:
        required: true
env:
  REGION_ID: us-east-1
  CLUSTER_ID: cfc647c22fd6848b5a602ad4d7470632b

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set K8S context
        uses: aliyun/ack-set-context@v1
        with:
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
          cluster-id: "${{ env.CLUSTER_ID }}"
      - uses: azure/setup-kubectl@v3
        with:
          version: ${{ inputs.version }} # default is latest stable
        id: install

      - name: Build Argo CD Application
        id: argo-cd
        uses: NaturalSelectionLabs/Daedalus/.github/actions/build-argocd-app
        with:
          name: daedalus
          namespace: guardian
          cluster: dev
          repo: ${{ github.repository }}
          revision: main
          image-name: ${{ inputs.images }}
          image-tag: ${{ inputs.tag }}
          helm-value-files: ${{ inputs.overrideFiles }}
          helm-release-name: ${{ inputs.releaseName }}
          helm-chart-url: ${{ inputs.repoUrl }}
          helm-chart-name: ${{ inputs.chart }}
          helm-chart-version: ${{ inputs.helm-chart-version }}
          kustomize-dir: ${{ inputs.kustomize-dir }}

      - name: Get the output yaml
        run: echo "${{ steps.argo-cd.outputs.app }}"
      - name: Deploy to Argo
        run: echo "${{ steps.argo-cd.outputs.app }}" | kubectl apply -f -
