name: Build and Deploy
on:
  push:
    branches:
      - dev
    tags:
      - v*
jobs:
  deploy-v3-dev:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v3-tpl.yaml@dev
    with:
      images: rss3/daedalus
      tag: latest
      cluster: dev
      namespace: guardian
      releaseName: daedalus
      revision: main
      dir: deploy/dev
    secrets: inherit
#  deploy-prod:
#    if: startsWith(github.ref, 'refs/tags/v')
#    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-tpl.yaml@main
#    needs:
#      - version
#      - build
#      - deploy-dev
#    with:
#      images: rss3/daedalus
#      tag: ${{ needs.version.outputs.version }}
#      cluster: prod
#      namespace: guardian
#      chart: web-app
#      releaseName: daedalus
#      overrideFiles: |
#        deploy/prod/values.yaml
#    secrets: inherit
