# deploy to kubernetes workflow
name: Deploy to Kubernetes
on:
  workflow_call:
    inputs:
      version:
        description: "Kubectl version"
        default: "latest"
        required: false
        type: string
      cluster:
        description: "Kubernetes cluster"
        required: true
        type: string
      namespace:
        description: "Kubernetes cluster namespace"
        required: true
        type: string
      images:
        description: "The image name"
        required: true
        type: string
      tag:
        description: "The image tag"
        required: true
        type: string
      releaseName:
        description: "The release name"
        required: true
        type: string
      chart:
        description: "Helm chart"
        required: true
        type: string
      overrideFiles:
        description: "Override files"
        required: false
        type: string
        default: values.yaml
      overrides:
        description: "Override values"
        required: false
        type: string
      repoUrl:
        description: "Helm repo url"
        required: false
        type: string
        default: "https://naturalselectionlabs.github.io/helm-charts"
      manifests:
        description: "Manifests"
        required: false
        type: string

env:
  REGION_ID: us-east-1
  DEV_ACK_CLUSTER_ID: cd1d0ffc40b5242b39ddda1864e71e30d
  PROD_ACK_CLUSTER_ID: cfc647c22fd6848b5a602ad4d7470632b

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Cluster ID
        run: |
          if [ "${{ inputs.cluster }}" == "dev" ]; then
            echo "CLUSTER_ID=${{ env.DEV_ACK_CLUSTER_ID }}" >> $GITHUB_ENV
          elif [ "${{ inputs.cluster }}" == "prod" ]; then
            echo "CLUSTER_ID=${{ env.PROD_ACK_CLUSTER_ID }}" >> $GITHUB_ENV
          fi
      - name: Set K8S context
        uses: aliyun/ack-set-context@v1
        with:
          access-key-id: "${{ secrets.ACCESS_KEY_ID }}"
          access-key-secret: "${{ secrets.ACCESS_KEY_SECRET }}"
          cluster-id: "${{ env.CLUSTER_ID }}"
      - uses: azure/setup-kubectl@v3
        with:
          version: ${{ inputs.version }} # default is latest stable
        id: install
      # use helm template render yaml to template.yaml
      - name: Download Helm chart to local path
        run: |
          helm repo add naturalselectionlabs https://naturalselectionlabs.github.io/helm-charts
          helm repo update
          helm pull naturalselectionlabs/${{ inputs.chart }} --untar
      - uses: azure/k8s-bake@v2.4
        with:
          renderEngine: helm
          helmChart: "./${{ inputs.chart }}"
          helm-version: "latest"
          overrideFiles: "${{ inputs.overrideFiles }}"
          overrides: "${{ inputs.overrides }}"
          releaseName: "${{ inputs.releaseName }}"
        id: bake

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          namespace: "${{ inputs.namespace }}"
          images: ${{ inputs.images }}:${{ inputs.tag }}
          manifests: |
            ${{ steps.bake.outputs.manifestsBundle }}
            ${{ inputs.manifests }}
