name: Build and Deploy
on:
  push:
    branches:
      - main
    tags:
      - v*
jobs:
  version:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version-without-v }}
    steps:
      - id: get_version
        uses: battila7/get-version-action@v2
  build:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/docker-tpl.yaml@main
    with:
      images: rss3/daedalus
      context: .
      dockerfile: ./Dockerfile
    secrets: inherit
  deploy-dev:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/daedalus
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: guardian
      chart: web-app
      releaseName: daedalus
      overrideFiles: |
        deploy/dev/values.yaml
    secrets: inherit
  deploy-v2-dev:
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-v2-tpl.yaml@main
    needs:
      - build
    with:
      images: rss3/daedalus
      tag: sha-${{ github.sha }}
      cluster: dev
      namespace: guardian
      chart: web-app
      releaseName: daedalus
      overrideFiles: |
        deploy/dev/values.yaml
    secrets: inherit
  deploy-prod:
    if: startsWith(github.ref, 'refs/tags/v')
    uses: NaturalSelectionLabs/Daedalus/.github/workflows/deploy-tpl.yaml@main
    needs:
      - version
      - build
      - deploy-dev
    with:
      images: rss3/daedalus
      tag: ${{ needs.version.outputs.version }}
      cluster: prod
      namespace: guardian
      chart: web-app
      releaseName: daedalus
      overrideFiles: |
        deploy/prod/values.yaml
    secrets: inherit
